import datetime
from datetime import date
import streamlit as st 
import os
import openai
st.set_page_config(
    page_title="Get Started Today",
    page_icon="🌱",
)

def get_today_date():
    today = date.today()
    return today.strftime("%Y-%m-%d")

openai.api_key = os.environ["OPENAI_API_KEY"]
def get_completion(system_prompt, user_prompt, model="gpt-3.5-turbo"):
   completion = openai.chat.completions.create(
        model=model,
        messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
        ]
    )
   return completion.choices[0].message.content

st.header(":green[Get Started Today] 🌱", divider="rainbow")
# st.markdown("With :violet[**AspireAI**], you can develop SMART goals, explore extracurriculars, and find courses that align with your career aspirations—all supported by tailored resources and expert guidance.")

col1, col2 = st.columns([3,2])
with col1:
    st.subheader("🎯 Develop SMART Goals")
    options = ["Resume Building", "Job or Internship Search", "Skill Development", "Other"]
    o = st.radio("**Type of Goal:**", options)
    if o == "Other":
        free_text = st.text_input("Please specify your goal type:")
with col2:
    st.image("BUS118i/pages/images/SG.webp")

s = st.text_input("""
:blue-background[:blue[**Specific:**]] What career goal do you want to accomplish? Please provide as much detail as you can.   
:gray[(Example: “Secure a summer internship in [my desired field] by applying to at least 10 positions a week.")] """)

M,A,RT = st.columns([2,3,3])
   
with M:
    options = ["Resume reviews", "Jobs applied", "Events attended", "Other"]
    m = st.radio(":green-background[:green[**Measurable:**]] How will you track your progress?", options)
    if m == "Other":
        free_text = st.text_input("Please specify your metrics:")

with A:
    a = st.text_area(":orange-background[:orange[**Achievable:**]] List any skills/resources you have that are relevant to this goal:",height=100)
with RT:
    options = ["Career Advancement", "Skill Development", "Job Security", "Professional Networking", "Higher Job Satisfaction", "Increased Confidence", "Other"]
    r = st.multiselect(
    ":red-background[:red[**Relevant:**]] What are the benefits?", options)
    if "Other" in r:
        other_option = st.text_input("Please specify the benefits:")
        if other_option:
            r.remove("Other")
            r.append(other_option)
    t = st.date_input(":violet-background[:violet[**Time-bound:**]] Enter your target deadline", value=None, format="MM/DD/YYYY")

system_role = """You are AspireAI, a professional business career advisor for college students.
    Use the student's input to develop a detailed one to two sentence SMART goal. Make it easy for college students to understand. Include the target deadline in Month Day, Year format.
    Then, provide specific action steps with due dates using the suggested deadline starting with today's date: """ + get_today_date() + """
    Format it like this, with 3 to 7 action steps:
    1. bolded sentence [action step].
    - italicize "Estimated Completion Time:" [time it would take to complete each task by minutes/hours]
    - italicize "Complete by" [suggested deadline in %m/%d/%Y]

    2. bolded sentence [action step].
    - italicize "Estimated Completion Time:" [time it would take to complete each task by minutes/hours]
    - italicize "Complete by" [suggested deadline in %m/%d/%Y]
    """

system_role2 = "Provide a real motivational quotes with the people who came up with them. make it for college students who are exploring their business career paths. The format is quote —person"

if st.button("Generate your SMART Goal & Action Plan"):
    r_string = ', '.join(r)
    if t is not None:
        t_string = t.strftime("%m/%d/%Y")
    else:
        t_string = "No deadline set"
    prompt = "My goal type is:" + o + ". My S is " + s + ". My M is " + m + ". My skills/resources are " + a + ". My long-term career aspirations are " + r_string + ". My T is " + t_string
    st.write(get_completion(system_role, prompt))
#    st.caption(":red[NOTE: These action steps are generated by AI and may not completely align with your specific career goals. Please review and modify them as needed to better suit your aspirations.]")
    prompt2 = "Format it as quote —person"
    st.subheader(get_completion(system_role2, prompt2))
    st.write(":violet[Thank you for using **AspireAI**! We're excited to help you on your journey to a successful business career. This tool was created by Kiley Huynh to support your growth. Best of luck in all your future endeavors!]")
